default_stages: [pre-commit]

repos:
  # 1. Official uv hooks (from astral-sh/uv-pre-commit)
  #    - uv-lock: Ensures your uv.lock file is up-to-date with pyproject.toml changes.
  #      This is crucial for reproducible environments managed by uv.
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.0
    hooks:
      - id: uv-lock
        name: Update uv.lock
        description: Ensures uv.lock is up-to-date with pyproject.toml/requirements.in.

  # 2. Ruff (from astral-sh/ruff-pre-commit)
  #    Ruff is an extremely fast Python linter and formatter.
  #    It can replace Flake8, Black, isort, and more, making it a powerful single tool.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        name: Run Ruff Linter
        description: Fixes linting issues with Ruff.
        args: [--fix, --exit-non-zero-on-fix]
        # --fix: Automatically fixes fixable linting errors.
        # --exit-non-zero-on-fix: Makes the hook fail if any fixes were applied.
      - id: ruff-format
        name: Run Ruff Formatter
        description: Formats Python code with Ruff.

  # 3. Mypy (from pre-commit/mirrors-mypy)
  #    Static type checking. This complements Ruff and uv well.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        name: Run Mypy Type Checker
        description: Checks Python code for type errors.

  # 4. General purpose hooks (from pre-commit/pre-commit-hooks)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: Ensure Trailing Newline
      - id: check-yaml
        name: Check YAML Syntax
      - id: check-added-large-files
        name: Prevent Large File Commits
        args: [--maxkb=500]
      - id: check-merge-conflict
        name: Check for Merge Conflict Artifacts
      - id: debug-statements
        name: Check for Debug Statements
      - id: check-json
        name: Check JSON Syntax
      - id: detect-private-key
        name: Detect Private Keys
